In [1]:
# Import Libraries
import pandas as pd
import sqlalchemy as sql

In [2]:
# EVP Location File to Load 
file_to_load = ".\Resources\Electric_Vehicle_Population_Data.csv"

# Read Electric_Vehicle_Population_Data File and store into Pandas data frame
WA_EVP_Location_data = pd.read_csv(file_to_load)

WA_EVP_Location_data.head()

,VIN (1-10),County,City,State,ZIP Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location
0,JN1AZ0CPXB,King,BELLEVUE,WA,98006,2011,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,73,0,41.0,108619647,NaN
1,5YJXCBE27H,King,BELLEVUE,WA,98006,2017,TESLA,MODEL X,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,200,0,41.0,132161060,NaN
2,3C3CFFGE7H,King,SEATTLE,WA,98109,2017,FIAT,500,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,84,0,36.0,132224858,POINT (-122.346385 47.630685)
3,5YJSA1E21J,King,BELLEVUE,WA,98006,2018,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,249,0,41.0,141069169,NaN
4,1FADP5CU4D,Pend Oreille,NEWPORT,WA,99156,2013,FORD,C-MAX,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,19,0,7.0,148318516,POINT (-117.183015 48.216812)

In [3]:
#Refine Dataframe
WA_EVP_Location_clean_data = WA_EVP_Location_data[["VIN (1-10)", "County", "City", "ZIP Code", "Model Year", "Make", "Model", "Electric Range"]]
WA_EVP_Location_data

WA_EVP_Location_clean_data.head()

,VIN (1-10),County,City,ZIP Code,Model Year,Make,Model,Electric Range
0,JN1AZ0CPXB,King,BELLEVUE,98006,2011,NISSAN,LEAF,73
1,5YJXCBE27H,King,BELLEVUE,98006,2017,TESLA,MODEL X,200
2,3C3CFFGE7H,King,SEATTLE,98109,2017,FIAT,500,84
3,5YJSA1E21J,King,BELLEVUE,98006,2018,TESLA,MODEL S,249
4,1FADP5CU4D,Pend Oreille,NEWPORT,99156,2013,FORD,C-MAX,19

In [4]:
# Save the WA_EVP_Location_clean_data dataframe as a csv
WA_EVP_Location_clean_data.to_csv('.\\Resources\WA_EVP_Location.csv', index = "False")

In [5]:
# EVP Registration File to Load 
file_to_load = ".\Resources\wa_ev_registrations_publicCC.csv"

# Read Electric_Vehicle_Population_Data File and store into Pandas data frame
WA_EVP_Registration_data = pd.read_csv(file_to_load)

WA_EVP_Registration_data.head()

,Vehicle ID,ZIP Code,Registration Valid Date,VIN Prefix,VIN Model Year,DMV ID,DMV ID Complete,DMV Snapshot,Registration Expiration Date,State Abbreviation,Geography,Vehicle Name,Technology
0,WA-044-10032256,98116,20/12/2021,1G1FZ6S0,L,44,WA44,WA DMV Direct (12/20/2021),NaN,WA,ZIP Code,Chevrolet Bolt EV,BEV
1,WA-044-118565170,98040,20/12/2021,1N4AZ0CP,D,44,WA44,WA DMV Direct (12/20/2021),NaN,WA,ZIP Code,Nissan Leaf,BEV
2,WA-044-176510946,98801,20/12/2021,5YJYGDEE,M,44,WA44,WA DMV Direct (12/20/2021),NaN,WA,ZIP Code,Tesla Model Y,BEV
3,WA-044-172434328,98021,20/12/2021,5YJ3E1EA,M,44,WA44,WA DMV Direct (12/20/2021),NaN,WA,ZIP Code,Tesla Model 3,BEV
4,WA-044-172658237,98056,20/12/2021,5YJYGDEE,M,44,WA44,WA DMV Direct (12/20/2021),NaN,WA,ZIP Code,Tesla Model Y,BEV

In [6]:
#Refine Dataframe
WA_EVP_Registration_clean_data = WA_EVP_Registration_data[["Vehicle ID", "ZIP Code", "VIN Prefix", "Vehicle Name", "Technology"]]
WA_EVP_Registration_clean_data

WA_EVP_Registration_clean_data.head()

         Vehicle ID  ZIP Code VIN Prefix       Vehicle Name Technology
0   WA-044-10032256     98116   1G1FZ6S0  Chevrolet Bolt EV        BEV
1  WA-044-118565170     98040   1N4AZ0CP        Nissan Leaf        BEV
2  WA-044-176510946     98801   5YJYGDEE      Tesla Model Y        BEV
3  WA-044-172434328     98021   5YJ3E1EA      Tesla Model 3        BEV
4  WA-044-172658237     98056   5YJYGDEE      Tesla Model Y        BEV

In [7]:
# Save the WA_EVP_Location_clean_data dataframe as a csv
WA_EVP_Registration_clean_data.to_csv('.\\Resources\WA_EVP_Registrations.csv', index = "False")